Pipenv setup & Project README
Jacks0N23/findMusicLinksBot pull request #1
Opened 2020-05-05 01:16 UTC by awave1

more about pipenv - https://github.com/pypa/pipenv

2020-05-05 14:32 UTC, Jacks0N23 requested changes

2020-05-05 14:32 UTC, Jacks0N23 commented on main.py
> +    """
я знал, что ты придёшь и поправишь мой английский)

2020-05-05 14:32 UTC, Jacks0N23 commented on main.py
> +    """
надо бы это тоже в конфиг унести

2020-05-05 14:32 UTC, Jacks0N23 commented on main.py
> +@server.route("/bot", methods=["POST"])
чем тебе одинарные кавычки не угодили?)

2020-05-05 14:32 UTC, Jacks0N23 commented on spotify.py
> +    client_id=cid, client_secret=secret
чем тебе в одну строку не понравилось? оно вроде влезало

2020-05-05 14:32 UTC, Jacks0N23 commented on README.md
> +## 🤝 Contributing
добавь тогда ещё
Contributors:
и укажи себя)

2020-05-05 14:32 UTC, Jacks0N23 commented on Pipfile
> +yandex-music = "==0.1.2"
а тут меньше зависимостей чем в requirements, это связано с тем, что остальные нужны для pipenv?

2020-05-05 15:43 UTC, Jacks0N23 commented
этот принимаю короче, но вечером жду второй)

2020-05-05 15:43 UTC, merged

2020-05-06 01:57 UTC, awave1 commented on Pipfile
> +yandex-music = "==0.1.2"
не, просто остальные тянутся сами для каждой либы